name = "BibParser"
uuid = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
authors = ["azzaare <jf@baffier.fr>"]
version = "0.1.18"

[deps]
BibInternal = "2027ae74-3657-4b95-ae00-e2f7d55c3e64"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
BibInternal = "0.3"
DataStructures = "0.18"
julia = "1.4"
